### ISSUE TITLE
Panic on bad server-url

### ISSUE THREAD

**Issue by kierarad** [gocd-contrib/gocd-cli#21]
Omitting /go

**Comment by marques-work** [comment]
Actually, I believe the panic I saw was not related to `/go` -- that was a coincidence. Omitting `/go` failed somewhat silently.

The panic was caused by a bug in `crypto/x509` for darwin builds of golang after `1.11.5`. See https://github.com/golang/go/issues/30763

**Comment by marques-work** [comment]
Reverting to 1.11.5 solves this issue.

**Comment by marques-work** [comment]
Additionally, we need to validate the server base url before issuing a request as the user may manually modify the `settings.yaml`, thereby circumventing the validations provided through the `config` command; this leads to silent failures. Validating before sending a request should provide this missing coverage.

See commit: e144a9816fbc954c425668020263ed0662d90d4d
