### ISSUE TITLE
Provide an option to choose auth method 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd-contrib/gocd-cli#36]
If both auth basic and auth token are configured, provide an option to choose auth method while executing cr commands.

**Comment by marques-work** [comment]
@varshavaradarajan I'm curious as to what the use case is? Currently, you can only configure 1 method as the `auth.type` key can only be set to one value.

If the scenario you had in mind was to support multiple profiles, this can be achieved by having more than 1 `settings.yaml` file, and specifying a `--config` location. Maybe not super-ideal, but that works.

**Comment by marques-work** [comment]
@varshavaradarajan also worth mentioning, the gocd-cli config shouldn’t let you configure both auth types in a single file. There was a bug that merged the two during if one tried to configure both, but that has been fixed. If you need both, consider using two separate `settings.yaml` files

**Comment by varshavaradarajan** [comment]
Thanks @marques-work. If there is a convenient option to choose between the auth methods, that's good. Closing this issue.
