### ISSUE TITLE
No Project License

### ISSUE THREAD

**Issue by jhurley1** [gocd-contrib/gocd-cli#46]
Hello,

The work you are doing here looks interesting but I don't see in the code or documentation what license this work is being made available under.  Can you provide a license file or clarify this so that people interested in this project understand terms and use?  Thanks!

**Comment by marques-work** [comment]
Hi there @jhurley1 - I've just added a [LICENSE file](https://github.com/gocd-contrib/gocd-cli/blob/master/LICENSE). It's Apache 2.0 like the rest of GoCD. Sorry for the confusion!
